baseURL: "https://hifranvilla.dev/"
languageCode: "es-es"
title: "Fran Villa"
theme: "PaperMod"

paginate: 10
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true

taxonomies:
  category: categories
  tag: tags

params:
  env: production
  title: "Fran Villa"
  description: "Notas de un developer full-stack aprendiendo Swift/SwiftUI en público"
  keywords: [Swift, SwiftUI, iOS, desarrollo]
  author: "Fran Villa"
  DateFormat: "2 January 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  socialIcons:
    - name: github
      url: "https://github.com/FranVilla90"
    - name: linkedin
      url: "https://www.linkedin.com/in/francisco-josé-villa-mejias-993196215/"
    - name: carrd
      url: "https://franvilla.carrd.co"
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

menu:
  main:
    - identifier: indice
      name: Índice
      url: /indice/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: sobre-mi
      name: Sobre mí
      url: /sobre-mi/
      weight: 25
    - identifier: search
      name: Buscar
      url: /search/
      weight: 30

outputs:
  home:
    - HTML
    - RSS
    - JSON



